### ISSUE TITLE
Ajouter un "sensor" avec state_class "total_increasing"

### ISSUE THREAD

**Issue by mdeweerd** [Thom-x/HomeAssistant_Gazpar#4]
La fonctionnalité "Energy" devient accessible (entre outre) lorsque le sensor a un "state_class" qui vaut "total_increasing" et qui a une unité ~~"kWh"~~ "m³".

Sur un module Zigbee qui propose le comptage, j'ai pu ajouter cette classe dans "customize.yaml" comme ceci:
```yaml
sensor.current_summation:
  state_class: total_increasing
```

L'intégration gazpar remonte la consommation de J-2, sans fournir de date à laquelle cette consommation correspond.
L'intégration ne remonte pas de total, et sans date, il est un peu risqué de faire la somme sur la simple base que la consommation a changé.  J'ai vérifié mon historique et j'ai par exemple deux jour de suite à 60kWh en avril, deux jours de suite à 9kWh et à 10kWh en juin, et 3 jours de suite à 9kWh en juin également . 

Ma demande est la suivante: ajouter un sensor qui se comporte comme un compteur en kWh.
C'est réalisable en ajoutant un state qui représente la date de la dernière consommation, et un state qui représente le total.  Ce total serait augmenté de la valeur retrouvée depuis l'API lorsque le jour change.
J

(Autre chose: actuellement l'integration se mets à jour tous les 30 minutes, mais cela me semble trop régulier compte tenu de la périodicité de la mise à jour.  Cela pourrait être optimisé en répétant la requête seulement tant que la conso de J-2 n'a pas été obtenu, et la commencer à partir d'une heure raissonnable - sinon mettre à jour toutes les 3 heures me semble suffisant, et à l'installation).

**Comment by mdeweerd** [comment]
En tant que solution intermédiaire, j'ai créé un compteur dans ma configuration qui est incrémenté de la valeur connue à 8h le matin.
Et puis j'ai découvert que HA s'attend à de m3 pour compter le gaz dans "Energie".
Donc j'ai converti les kWh en m3 avec une conversion fixe.
Idéalement faudrait remonter les m3 depuis GRDF également, mais directement comme "sensor"/compteur .

Définition compteur en tant que "counter" pour faire les calculs.:
```yaml
counter:
  gas_consumption:
    initial: 0
    restore: true
```

"Energy" veut un "sensor" en m3 pour le gaz, j'ai crée un compter en kWh aussi, en supposant une évolution future pour "Energy".
```
- platform: template
  sensors:
    gas_consumption_kwh:
      friendly_name: "Gaz (kWh)"
      unit_of_measurement: "kWh"
      value_template: "{{ states('counter.gas_consumption') }}"
    gas_consumption_m3:
      friendly_name: "Gaz (m³)"
      unit_of_measurement: "m³"
      value_template: "{{ states('counter.gas_consumption') | float / 11.16 }}"
```

Customisation dans 'customize.yaml' pour en faire des "total_increasing", les "unit_of_measurement" ne sont probablement pas utiles.

```yaml
sensor.gas_consumption_kwh:
  state_class: total_increasing
  unit_of_measurement: kWh
sensor.gas_consumption_m3:
  state_class: total_increasing
  unit_of_measurement: "m³"
```

Automatisation pour ajouter le rélevé de J-2 au total dans le compteur - pour le moment à 8h :
```yaml
alias: Accumuler consommation Gazpar
description: Ajoute la consommation du jour précédent au compteur global
trigger:
  - platform: time
    at: '08:00:00'
condition: []
action:
  - service: counter.configure
    target:
      entity_id: counter.gas_consumption
    data:
      value: >-
        {{ states('counter.gas_consumption') | float +
        states('sensor.compteur_gazpar') | float }}
mode: single
```

Customize.yaml doit être lu avec ceci dans `configuration.yaml`:
```yaml
homeassistant:
  customize: !include customize.yaml
```
